# -*- coding: utf-8 -*-
"""RMSProp Univariate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zghq17XdPkTKs9JrTSqAvVqLjUEN_ITL
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop
from keras.callbacks import EarlyStopping

"""Deep Neural Network with RMSProp Optimization

Import dataset
"""

df1 = pd.read_excel('data penjualan tembakau.xlsx')
df1.head()

len(df1)

def convert2matrix(data_arr, look_back):
  X, Y = [], []
  for i in range(len(data_arr)-look_back):
    d=i+look_back
    X.append(data_arr[i:d])
    Y.append(data_arr[d])
  return np.array(X), np.array(Y)

"""Splitting data"""

#Split data set into testing dataset and train dataset
train_size = 292
train, test =df1.values[0:train_size,1],df1.values[train_size:len(df1.values),1]
# setup look_back window
look_back = 30

#convert dataset into right shape in order to input into the DNN
trainX, trainY = convert2matrix(train, look_back)
testX, testY = convert2matrix(test, look_back)

trainX = trainX.astype('float32')
trainY = trainY.astype('float32')
testX = testX.astype('float32')
testY = testY.astype('float32')

"""Define neural network shape and compile model"""

from keras.models import Sequential
from keras.layers import Dense
def model_dnn(look_back):
    model=Sequential()
    model.add(Dense(units=32, input_dim=look_back, activation='relu'))
    model.add(Dense(8, activation='relu'))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error',  optimizer=RMSprop(),metrics = ['mse', 'mae'])
    return model

"""Fit Model"""

model=model_dnn(look_back)
history=model.fit(trainX,trainY, epochs=100, batch_size=30, verbose=1, validation_data=(testX,testY),callbacks=[EarlyStopping(monitor='val_loss', patience=10)],shuffle=False)

"""Model evaluation"""

def model_loss(history):
    plt.figure(figsize=(8,4))
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Test Loss')
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epochs')
    plt.legend(loc='upper right')
    plt.show();

# Commented out IPython magic to ensure Python compatibility.
train_score = model.evaluate(trainX, trainY, verbose=0)
print('Train Root Mean Squared Error(RMSE): %.2f; Train Mean Absolute Error(MAE) : %.2f '
# % (np.sqrt(train_score[1]), train_score[2]))
test_score = model.evaluate(testX, testY, verbose=0)
print('Test Root Mean Squared Error(RMSE): %.2f; Test Mean Absolute Error(MAE) : %.2f '
# % (np.sqrt(test_score[1]), test_score[2]))
model_loss(history)

"""Visualizing Prediction"""

def prediction_plot(testY, test_predict):
      len_prediction=[x for x in range(len(testY))]
      plt.figure(figsize=(8,4))
      plt.plot(len_prediction, testY, marker='.', label="actual")
      plt.plot(len_prediction, test_predict, 'r', label="prediction")
      plt.tight_layout()
      sns.despine(top=True)
      plt.subplots_adjust(left=0.07)
      plt.ylabel('Harga Tembakau', size=15)
      plt.xlabel('Hari Ke-', size=15)
      plt.legend(fontsize=15)
      plt.show();

"""Train Data Fitted Plot"""

prediction_plot(trainY, model.predict(trainX))

"""Test Data Fitted Plot"""

prediction_plot(testY, model.predict(testX))

"""Forecasting"""

# Lakukan peramalan untuk 10 hari ke depan
last_data = testX[-1]  # Data terakhir dari data asli
forecast = []

for _ in range(10): # Jika ingin melakukan peramalan untuk lebih dari 10 hari ke depan, silahkan ubah angka 10 yang ada di range()
    prediction = model.predict(np.array([last_data]))  # Lakukan peramalan untuk data terakhir
    forecast.append(prediction.flatten()[0])  # Tambahkan hasil peramalan ke dalam forecast
    last_data = np.append(last_data[1:], prediction)  # Update data terakhir dengan hasil peramalan

print(forecast)

forecast_mat = np.array(forecast)
print(forecast_mat)

# Plot hasil forecast
plt.plot(range(0, len(forecast_mat)), forecast_mat.flatten(), label='Hasil Peramalan')
plt.xlabel('Hari Ke-')
plt.ylabel('Harga Tembakau')
plt.legend()
plt.show()